### ISSUE TITLE
Improvement: run the actions/checkout as part of the entrypoint.sh

### ISSUE THREAD

**Issue by jpvalery** [jpvalery/yarn-percy-ci#2]
This could be a better all-in-one solution if I could add the checkout as part of the entrypoint.sh. 

Right now, I have to use this structure
```yaml
 steps:
    - uses: actions/checkout@v1 
    - uses: jpvalery/yarn-percy-ci@master
```

whereas if I added the checkout to the entrypoint.sh, the workflow could just be
```yaml
 steps:
    - uses: jpvalery/yarn-percy-ci@master
```
